# Generated by Django 5.1.5 on 2025-02-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allow_org_access",
            field=models.BooleanField(
                default=False,
                help_text="If True, other members of the same Organization can view this profile.",
            ),
        ),
    ]
