# Generated by Django 5.1.5 on 2025-02-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_allow_org_access'),
        ('profiles', '0002_userprofile_area_of_interests_and_more'),
    ]

    operations = [
    ]
