# Generated by Django 5.1.5 on 2025-02-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_merge_20250206_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='long_term_reading_status',
            field=models.CharField(default='started', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(default='english', max_length=50),
        ),
    ]
