# Generated by Django 5.1.5 on 2025-02-01 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Handler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("access_list", models.JSONField(blank=True, default=list, null=True)),
                (
                    "allowed_internal_roles",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("app_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=255)),
                ("method_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("access_list", models.JSONField(blank=True, default=list, null=True)),
                (
                    "allowed_internal_roles",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("base_url", models.URLField(blank=True, max_length=255)),
                ("auth_method", models.CharField(default="Bearer", max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("access_list", models.JSONField(blank=True, default=list, null=True)),
                (
                    "allowed_internal_roles",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("path_params", models.JSONField(blank=True, default=list, null=True)),
                ("description", models.TextField(blank=True)),
                ("extra_params", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "handlers",
                    models.ManyToManyField(
                        blank=True, related_name="endpoints", to="conduit.handler"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="conduit.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("access_list", models.JSONField(blank=True, default=list, null=True)),
                (
                    "allowed_internal_roles",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("full_url", models.TextField(default="")),
                ("request_data", models.JSONField(default=dict)),
                ("response_data", models.JSONField(default=dict)),
                ("status_code", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conduit.endpoint",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conduit.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
