# Generated by Django 5.1.5 on 2025-02-05 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("access_list", models.JSONField(blank=True, default=list, null=True)),
                (
                    "allowed_internal_roles",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("max_seats", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_by_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("access_list", models.JSONField(blank=True, default=list, null=True)),
                (
                    "allowed_internal_roles",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
