# Generated by Django 5.1.5 on 2025-02-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_conversation_is_active_and_more'),
        ('assistant', '0002_conversation_assistant_id_conversation_session_id_and_more'),
    ]

    operations = [
    ]
