# Generated by Django 5.1.5 on 2025-02-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_merge_20250206_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
